# Generated by Django 3.1.4 on 2020-12-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.SlugField(default=0, help_text='Обязательное поле. Укажите телефон в формате +7 XXX XXX-XX-XX.', verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
