# Generated by Django 3.1.7 on 2021-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201226_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.SlugField(help_text='Обязательное поле. Укажите телефон в формате 8-XXX-XXX-XX-XX.', verbose_name='Телефон'),
        ),
    ]
