# Generated by Django 3.2 on 2021-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manufacturer',
            field=models.TextField(choices=[('ДОЛ ХЛЕБ', 'ДОЛ ХЛЕБ'), ('ООО «Сладкая мечта», ИНН 7724870668, КПП 772401001, 115477, г. Москва, ул. Промышленная, д.10', 'СЛАТИНИ')], default='ДОЛ ХЛЕБ', max_length=255),
        ),
    ]
